### PR TITLE
Rename index.test.js to index.test.cjs

### PR DESCRIPTION
**Pull request by remcohaszing**
### Initial checklist

*   [x] I read the support docs 
*   [x] I read the contributing guide 
*   [x] I agree to follow the code of conduct 
*   [x] I searched issues and couldn’t find anything (or linked relevant results below) 
*   [x] If applicable, I’ve added docs and tests

### Description of changes

This makes XO not complain about CommonJS syntax by default.

### CODE REVIEW

**Review by JounQin — CHANGES_REQUESTED** [review]
type: module is not enabled at all

**Comment by remcohaszing** [comment]
Nope, and it shouldn’t be. VSCode only support CommonJS extensions. However, XO assumes `.js` files are ESM.

**Comment by JounQin** [comment]
That's xo's issue then.

**Review by ChristianMurphy — APPROVED** [review]
The functionality in xo appears to be intentional https://github.com/sindresorhus/eslint-plugin-unicorn/issues/1067

And, in my opinion, the cjs extension is clear anyway

**Comment by JounQin** [comment]
> The functionality in xo appears to be intentional [sindresorhus/eslint-plugin-unicorn#1067](https://github.com/sindresorhus/eslint-plugin-unicorn/issues/1067)
> 
> And, in my opinion, the cjs extension is clear anyway

I understand it's intentional, but I think that rule is a bit overkill, the developers are responsible to understand what does `.js` mean in a package without `type: module`. And `.js` is always preferred IMO.

**Comment by remcohaszing** [comment]
I personally have no strong feelings about this, but I prefer to adhere to the linting rules rather than disabling them.

**Comment by JounQin** [comment]
> I personally have no strong feelings about this, but I prefer to adhere to the linting rules rather than disabling them.

`eslint-plugin-unicorn`/`xo` is very opinionated IMO, and luckily we can just disable the unexpected rules.

**Review by wooorm — APPROVED** [review]

**Comment by wooorm** [comment]
The linter is very opinionated. That is intentional.
With that, comes that I find it very okay to turn opinionated rules off.
I have no strong feelings about this 🤷‍♂️

**Comment by remcohaszing** [comment]
Since this is purely stylistic and @JounQin seems to have the strongest opinion on this, let’s keep it as-is.

**Pull request closed without merging**
